---
- hosts: webserver
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker
        
    - name: Pull the docker image
      docker_image:
        name: "mhali/myapp_java:{{DOCKER_TAG}}"
        source: pull
        
    - name: create the container
      docker_container:
        name: "myapp_java"
        image: "mhali/myapp_java"
        state: present
        published_ports:
          - 0.0.0.0:8080:8080
